#springboot配置
server:
  # 当前项目运行端口号
  port: 1212
spring:
  application:
    # 项目名称
    name: gradleProject
  #数据库连接地址（数据库信息）
  datasource:
    url: jdbc:mysql://:3306/gradle_project?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    password: 127.0.0.1
    username: 123456
    max-active: 15
    min-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver

# redis 配置
redis:
  # 地址
  host:
  # 密码
  password:
  # 端口，默认为6379
  port: 6379
  # 数据库索引
  database: 0
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms
